spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/productsdb
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'